version: '3.8'

services:
  wallet-service:
    build: 
      context: ./backend/services/wallet
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DEBUG=false
      - PORT=3000
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
      - RABBITMQ_HOST=rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - rabbitmq

  order-service:
    build:
      context: ./backend/services/order
      dockerfile: Dockerfile
    environment:
      - DEBUG=false
      - PORT=5001
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    ports:
      - "3001:5001"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge



   